cd /dev #change directory to /dev directory

ls #list the files and directories in the /dev directory
cd /proc #Each number = a running process; change directory to /proc
cat cpuinfo #Shows information about the processor

#the root in linux (/) is the top level of the file system hierarchy, it contains all other files and directories in the system. It is the starting point for navigating the file system and is represented by a single forward slash (/). The root directory is owned by the root user and has special permissions that allow it to access and modify all files and directories on the system. It is important to be cautious when working with the root directory, as making changes to it can have significant consequences for the stability and security of the system., haz nothing to do with the root user, it is just the top level of the file system hierarchy. The root user is a separate concept that refers to the superuser account with administrative privileges in a Linux system.
#mounting directories in linux is the process of making a file system accessible at a specific point in the directory tree. This is done using the mount command, which allows you to attach a file system to a directory, making its contents available for use. For example, if you have a separate partition or external drive, you can mount it to a directory such as /mnt or /media to access its files. The mount command requires specifying the device or file system to be mounted and the target directory where it should be accessible. Once mounted, you can navigate and interact with the files and directories within that file system as if they were part of the main directory structure.
# the /media directory in Linux is a standard location for mounting removable media such as USB drives, CDs, and DVDs. When you insert a removable device into your computer, it is typically automatically mounted to a subdirectory within /media. For example, if you insert a USB drive, it may be mounted to /media/usb or /media/username/usb. This allows you to easily access the files on the removable media without needing to manually mount it each time. The /media directory serves as a convenient location for managing and accessing external storage devices in Linux. also, linux is case sensitive
#remeber to check the FHS (Filesystem Hierarchy Standard) for more information about the directory structure and organization in Linux. The FHS defines the standard layout of directories and files in a Linux system, providing guidelines for where different types of files should be located. It helps ensure consistency and compatibility across different Linux distributions and makes it easier for users and developers to navigate and understand the file system.

gcc saludo.c -o saludobin #this command compiles the C source code file named "saludo.c" and generates an executable binary file named "saludobin". The "gcc" command is the GNU Compiler Collection, which is used to compile C and C++ programs. The "-o" option specifies the output file name for the compiled binary. After running this command, you will have an executable file called "saludobin" that can be run in the terminal to execute the code contained in "saludo.c".
mv saludobin /bin #this command moves the file named "saludobin" to the /bin directory. The /bin directory is a standard location for storing essential binary executable files in Linux. By moving "saludobin" to /bin, it becomes accessible as a command that can be executed from anywhere in the terminal without needing to specify its full path. This allows users to run the "saludobin" command directly from the command line, making it more convenient to use.
sudo mv saludobin /bin #this command is similar to the previous one, but it uses "sudo" to execute the move operation with superuser privileges. This is necessary if the user does not have sufficient permissions to move the file to the /bin directory. By using "sudo", the user can temporarily elevate their privileges to perform administrative tasks, such as moving files to system directories like /bin. After running this command, "saludobin" will be moved to /bin and can be executed as a command from anywhere in the terminal.
ls /bin/saludobin #this command lists the file named "saludobin" in the /bin directory. It is used to verify that the file has been successfully moved to the /bin directory. If the file is present, it will be displayed in the output of the command. This allows the user to confirm that "saludobin" is now located in /bin and can be executed as a command from anywhere in the terminal.
saludobin #this command executes the "saludobin" binary file that was moved to the /bin directory. By running this command, the user can execute the code contained in "saludobin" and see its output in the terminal. This allows the user to interact with the program and see the results of its execution.
pwd #this command prints the current working directory in the terminal. It shows the full path of the directory that the user is currently in. This is useful for confirming your location in the file system and ensuring that you are in the correct directory before executing commands or accessing files.
cd / #this command changes the current working directory to the root directory (/) of the file system. The root directory is the top-level directory that contains all other files and directories in the system. By running this command, the user can navigate to the root directory and access its contents or perform operations from that location.
ls -F #this command lists the files and directories in the current directory, and the -F option adds a character to the end of each entry to indicate its type. For example, directories will have a trailing slash (/), executable files will have an asterisk (*), and symbolic links will have an at symbol (@). This helps users quickly identify the types of files and directories in the listing.


#the name if the archive is not saved on the inode, but in the directory that contains it.

