cd /dev #change directory to /dev directory

ls #list the files and directories in the /dev directory
cd /proc #Each number = a running process; change directory to /proc
cat cpuinfo #Shows information about the processor

#the root in linux (/) is the top level of the file system hierarchy, it contains all other files and directories in the system. It is the starting point for navigating the file system and is represented by a single forward slash (/). The root directory is owned by the root user and has special permissions that allow it to access and modify all files and directories on the system. It is important to be cautious when working with the root directory, as making changes to it can have significant consequences for the stability and security of the system., haz nothing to do with the root user, it is just the top level of the file system hierarchy. The root user is a separate concept that refers to the superuser account with administrative privileges in a Linux system.
#mounting directories in linux is the process of making a file system accessible at a specific point in the directory tree. This is done using the mount command, which allows you to attach a file system to a directory, making its contents available for use. For example, if you have a separate partition or external drive, you can mount it to a directory such as /mnt or /media to access its files. The mount command requires specifying the device or file system to be mounted and the target directory where it should be accessible. Once mounted, you can navigate and interact with the files and directories within that file system as if they were part of the main directory structure.
# the /media directory in Linux is a standard location for mounting removable media such as USB drives, CDs, and DVDs. When you insert a removable device into your computer, it is typically automatically mounted to a subdirectory within /media. For example, if you insert a USB drive, it may be mounted to /media/usb or /media/username/usb. This allows you to easily access the files on the removable media without needing to manually mount it each time. The /media directory serves as a convenient location for managing and accessing external storage devices in Linux. also, linux is case sensitive
#remeber to check the FHS (Filesystem Hierarchy Standard) for more information about the directory structure and organization in Linux. The FHS defines the standard layout of directories and files in a Linux system, providing guidelines for where different types of files should be located. It helps ensure consistency and compatibility across different Linux distributions and makes it easier for users and developers to navigate and understand the file system.

gcc saludo.c -o saludobin #this command compiles the C source code file named "saludo.c" and generates an executable binary file named "saludobin". The "gcc" command is the GNU Compiler Collection, which is used to compile C and C++ programs. The "-o" option specifies the output file name for the compiled binary. After running this command, you will have an executable file called "saludobin" that can be run in the terminal to execute the code contained in "saludo.c".
mv saludobin /bin #this command moves the file named "saludobin" to the /bin directory. The /bin directory is a standard location for storing essential binary executable files in Linux. By moving "saludobin" to /bin, it becomes accessible as a command that can be executed from anywhere in the terminal without needing to specify its full path. This allows users to run the "saludobin" command directly from the command line, making it more convenient to use.
sudo mv saludobin /bin #this command is similar to the previous one, but it uses "sudo" to execute the move operation with superuser privileges. This is necessary if the user does not have sufficient permissions to move the file to the /bin directory. By using "sudo", the user can temporarily elevate their privileges to perform administrative tasks, such as moving files to system directories like /bin. After running this command, "saludobin" will be moved to /bin and can be executed as a command from anywhere in the terminal.
ls /bin/saludobin #this command lists the file named "saludobin" in the /bin directory. It is used to verify that the file has been successfully moved to the /bin directory. If the file is present, it will be displayed in the output of the command. This allows the user to confirm that "saludobin" is now located in /bin and can be executed as a command from anywhere in the terminal.
saludobin #this command executes the "saludobin" binary file that was moved to the /bin directory. By running this command, the user can execute the code contained in "saludobin" and see its output in the terminal. This allows the user to interact with the program and see the results of its execution.
pwd #this command prints the current working directory in the terminal. It shows the full path of the directory that the user is currently in. This is useful for confirming your location in the file system and ensuring that you are in the correct directory before executing commands or accessing files.
cd / #this command changes the current working directory to the root directory (/) of the file system. The root directory is the top-level directory that contains all other files and directories in the system. By running this command, the user can navigate to the root directory and access its contents or perform operations from that location.
ls -F #this command lists the files and directories in the current directory, and the -F option adds a character to the end of each entry to indicate its type. For example, directories will have a trailing slash (/), executable files will have an asterisk (*), and symbolic links will have an at symbol (@). This helps users quickly identify the types of files and directories in the listing.
ls -i #this command lists the files and directories in the current directory, and the -i option displays the inode number of each file or directory. An inode is a data structure that stores information about a file or directory, such as its permissions, ownership, size, and location on the disk. By using this command, users can see the inode numbers associated with each file and directory, which can be useful for various purposes, such as troubleshooting or managing files based on their inodes.

#the name if the archive is not saved on the inode, but in the directory that contains it.
# the hard links are multiple directory entries that point to the same inode, meaning they refer to the same file on the disk. When you create a hard link, it creates another directory entry that points to the same inode as the original file. This allows you to have multiple names for the same file, and any changes made to the file through one of the links will be reflected in all other links since they all point to the same underlying data on the disk. Hard links are useful for creating shortcuts or aliases for files without duplicating their content, and they can only be created within the same file system.
#the symbolic links, also known as symlinks or soft links, are special types of files that act as pointers to other files or directories. Unlike hard links, symbolic links can point to files or directories located on different file systems. When you create a symbolic link, it creates a new file that contains a reference to the target file or directory. When you access the symbolic link, the operating system follows the reference and accesses the target file or directory. Symbolic links are useful for creating shortcuts or aliases for files and directories, and they can be easily identified by the "@" symbol at the end of their name when listed with the "ls -F" command. They are commonly used for organizing files and directories, providing alternative names, or creating links to frequently accessed files or directories.
#with hard links you cant merge disk partitions 
#in soft links, if you delete the original file, the symbolic link will become broken and will no longer point to a valid file or directory. This is because the symbolic link relies on the existence of the target file or directory to function properly. If the target is removed, the symbolic link will still exist but will not be able to access the intended content, resulting in an error when trying to access it. Therefore, it is important to be cautious when deleting files that have symbolic links pointing to them, as it can lead to broken links and potential issues with accessing the linked content. a paradigma of similar nature in programming are those in RUST
# Also, soft links liberate space.}
vmlinuz@ and vmlinuz.old@ #these are symbolic links that point to the current and previous versions of the Linux kernel, respectively. The "@" symbol at the end of their names indicates that they are symbolic links. The vmlinuz file is the compressed Linux kernel image that is loaded into memory during the boot process. By using symbolic links for these files, it allows for easy management and updating of the kernel without needing to change the actual file names or locations. When a new kernel version is installed, the symbolic link can be updated to point to the new kernel image, while still keeping the old version accessible through the vmlinuz.old link if needed.
#the linux kernel direction is typically located in the /boot directory, which contains the files necessary for booting the Linux operating system. The kernel image files, such as vmlinuz and vmlinuz.old, are usually found in this directory. The /boot directory also contains other important files related to the boot process, such as the initial RAM disk (initrd) images and the GRUB bootloader configuration files. It is important to note that the exact location of the kernel files may vary depending on the Linux distribution and configuration, but /boot is a common location for storing these critical files.
#the windows kernel is typically located in the C:\Windows\System32 directory. The kernel files in Windows are responsible for managing system resources, handling hardware interactions, and providing essential services for the operating system to function properly. The main kernel file in Windows is called "ntoskrnl.exe", which stands for "NT Operating System Kernel". This file contains the core components of the Windows kernel and is loaded into memory during the boot process. It is important to note that the exact location of the kernel files may vary depending on the version of Windows and the specific configuration of the system, but C:\Windows\System32 is a common location for storing these critical files.
